server:
  port: 80
spring:
  mail:
    host: smtp.qq.com
    username: 915950092@qq.com
    password: xsydehiaawrgbecf
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
  application:
    #应用的名称，可选
    name: xjbx
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xjbx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  redis:
    #password:   windows??root@1234  Linux?1234
    host: localhost
    database: 0
    port: 6379
  cache:
    redis:
      time-to-live: 1800000      #设置缓存过期时间  30分钟
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射      MP默认开启  可不写
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

xjbx:
  path: a